app1/urls.py
from django.urls import path
from app1.views import*
app_name='images2'
urlpatterns=[
    path('shiva/',shiva,name='shiva')
]

staticproject/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import*
import app1
urlpatterns = [
    path('admin/', admin.site.urls),
    path("subham/",subham,name='subham'),
    path("app1",include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def subham(request):
    return render(request,'images.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def shiva(request):
    return render(request,'images2.html')

templates/images.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <center>
        <h1>this is images</h1>
        <button><a href="{% url 'images2:shiva' %}">go to images2</a></button>
        <img src="{% static 'images/thumb-1920-1010687.jpg'  %}" alt="">
        
    </center>
</body>
</html>

templates/images2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
</head>
<body>
    <center>
        <h1>this is  images2</h1>
        <button><a href="{% url 'subham' %}">go to images</a></button>
        <img src="{% static 'images/eeer.jpg'%}" alt="{% url 'subham' %}">
    </center>
</body>
</html>